version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: postman/newman_ubuntu1404 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: 
          name: Test
          command: docker run hello-world
